//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather_Collect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather_Collect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_East_Coast {
            get {
                return ResourceManager.GetString("Config_East_Coast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.015.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+21&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.021.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Gateway {
            get {
                return ResourceManager.GetString("Config_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.015.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+21&quot;,&quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Japan {
            get {
                return ResourceManager.GetString("Config_Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;Japan&quot;,&quot;Current&quot;,&quot;http://www.jma.go.jp/jp/g3/images/asia/pdf/asas.pdf&quot;,&quot;0&quot;,&quot;http://www.jma.go.jp/jp/g3/images/asia/pdf/asas.pdf&quot;,&quot;0
        ///Satellite&quot;,&quot;IR&quot;,&quot;Disk&quot;,&quot;http://www.jma.go.jp/en/gms/imgs/6/infrared/0/|||TIME:yyyyMMddhhmm:30|||-00.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellite&quot;,&quot;Geocolour&quot;,&quot;Disk&quot;,&quot;http://rammb.cira.colostate.edu/ramsdis/online/images/himawari-8/full_disk_ahi_true_color/full_disk_ahi_true_color_|||TIME:yyyyMMddhhmmss:30|||.jpg&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellite&quot;,&quot;Geocolour&quot;,&quot;Japan&quot;,&quot;http://rammb.cira.colostate.edu/r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Japan_South {
            get {
                return ResourceManager.GetString("Config_Japan_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+06&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.006.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+12&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.012.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+18&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Oceania {
            get {
                return ResourceManager.GetString("Config_Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.006.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.012.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.018.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+21&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.024.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Philippines {
            get {
                return ResourceManager.GetString("Config_Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.006.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.012.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.018.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+21&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20101/current/mslp-precip/IDY20101.mslp-precip.024.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Philippines_Transit {
            get {
                return ResourceManager.GetString("Config_Philippines_Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_Resolute {
            get {
                return ResourceManager.GetString("Config_Resolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;Precip&quot;,&quot;+06&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.006.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+12&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.012.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+18&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.018.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+24&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.024.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///Satellit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_RIMPAC_Ex {
            get {
                return ResourceManager.GetString("Config_RIMPAC_Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_SAXA {
            get {
                return ResourceManager.GetString("Config_SAXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+03&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.003.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+09&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20300/current/mslp-precip/IDY20300.mslp-precip.009.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+15&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_West_Coast {
            get {
                return ResourceManager.GetString("Config_West_Coast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSLP&quot;,&quot;&quot;,&quot;Current&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.png&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDY00050.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;&quot;,&quot;Forecast&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.gif&quot;,&quot;0&quot;,&quot;http://www.bom.gov.au/fwo/IDG00074.pdf&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+06&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.006.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+12&quot;,&quot;http://www.bom.gov.au/charts_data/IDY20000/current/mslp-precip/IDY20000.mslp-precip.012.png&quot;,&quot;0&quot;,&quot;&quot;,&quot;0
        ///MSLP&quot;,&quot;Precip&quot;,&quot;+18&quot;,&quot;http://www.bom.gov. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_WestPac {
            get {
                return ResourceManager.GetString("Config_WestPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownloadFolder {
            get {
                object obj = ResourceManager.GetObject("DownloadFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownloadFolder27 {
            get {
                object obj = ResourceManager.GetObject("DownloadFolder27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
